import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "รับออกแบบและพัฒนาเว็ปไซต์ | Pengu Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
            {children}
      </body>
    </html>
  );
}
